# **Fine-Tuning a Pretrained BERT model**

## **Loading Dataset**

Dataset "rotten_tomatoes"

Dataset from Hugging Face

Movies reviews

Labels : 0 (negative), 1 (positive)

train_data =  dataframe with 8530 rows, two columns 'text, 'label'

test_data = dataframe with 1066 rows, , two columns 'text, 'label'

In [ ]:
from datasets import load_dataset
data = load_dataset("rotten_tomatoes")
train_data = data["train"]
test_data = data["test"]

README.md: 0.00B [00:00, ?B/s]

train.parquet:   0%|          | 0.00/699k [00:00<?, ?B/s]

validation.parquet:   0%|          | 0.00/90.0k [00:00<?, ?B/s]

test.parquet:   0%|          | 0.00/92.2k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/8530 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1066 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1066 [00:00<?, ? examples/s]

In [ ]:
from pprint import pprint
print(type(data))
print(data)
print("\n"*2+"Train data")
pprint(train_data[:2])
print("\n"*2+"Test data")
pprint(test_data[:2])

<class 'datasets.dataset_dict.DatasetDict'>
DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 8530
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 1066
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 1066
    })
})


Train data
{'label': [1, 1],
 'text': ['the rock is destined to be the 21st century\'s new " conan " and '
          "that he's going to make a splash even greater than arnold "
          'schwarzenegger , jean-claud van damme or steven segal .',
          'the gorgeously elaborate continuation of " the lord of the rings " '
          'trilogy is so huge that a column of words cannot adequately '
          "describe co-writer/director peter jackson's expanded vision of j . "
          "r . r . tolkien's middle-earth ."]}


Test data
{'label': [1, 1],
 'text': ['lovingly photographed in the manner of a golden book sprung to life '
          ', stuart little 2 manages sweetness largely without stickiness .',
          'consistently clever and suspenseful .']}

In [ ]:
train_data.filter(lambda example: example['label'] == 1)

Filter:   0%|          | 0/8530 [00:00<?, ? examples/s]

Dataset({
    features: ['text', 'label'],
    num_rows: 4265
})

In [ ]:
print(set(train_data['label']))

{0, 1}

# Classifier without fine-tuning

We create a pipeline with transformers.

2 inputs:

1.   The task
2.   The model

In [ ]:
from transformers import pipeline
pipe = pipeline(
    "text-classification",
    model="bert-base-cased"
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
texts=test_data['text']
labels = test_data['label']

In [ ]:
predictions = pipe(list(texts),batch_size=32)

In [ ]:
from sklearn.metrics import f1_score,accuracy_score, classification_report
label2id = {"LABEL_0": 0,"LABEL_1": 1}
preds=[label2id[pred['label']] for pred in predictions]
print(f"Unique predictions: {set(preds)}")  # likely only {0} or {1}
print(f"F1 Score : {f1_score(labels,preds,average='macro'):.4f}")
print(f"accuracy score : {accuracy_score(labels,preds):.4f}")
print(classification_report(labels,preds,zero_division=0))

Unique predictions: {0}
F1 Score : 0.3333
accuracy score : 0.5000
              precision    recall  f1-score   support

           0       0.50      1.00      0.67       533
           1       0.00      0.00      0.00       533

    accuracy                           0.50      1066
   macro avg       0.25      0.50      0.33      1066
weighted avg       0.25      0.50      0.33      1066

# **Fine-tuning a LLM for text classification**


**Step 1: Defining the model and tokenizer**

We select the model

We import

- **the model**: the option num_labels=2 indicates we are dealing with 2 possible outcomes

The loaded BERT model **automatically** construct a structure with a head capable to deal with 2 classification labels

**AutoModelForSequenceClassification**


*   We call the model for classification. The classification head on top is randomly initialized
*   Generic, model-agnostic wrapper
*   Automatically infers the correct model class from the checkpoint name or config
*   works with BERT, RoBERTa, DistilBERT, XLN, ALBERT,...
*   Recommended, flexible approach


- **the tokenizer** associated to the model

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
model_name = "bert-base-cased"
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,num_labels=2)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Note that the parameters of the classification heads are missing (randomly initialized) and need to be fine-tuned

In [ ]:
from transformers import AutoConfig
config = AutoConfig.from_pretrained('bert-base-cased')
print(config)
print(config.architectures)

BertConfig {
  "add_cross_attention": false,
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": null,
  "classifier_dropout": null,
  "eos_token_id": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "is_decoder": false,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "tie_word_embeddings": true,
  "transformers_version": "5.0.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 28996
}

['BertForMaskedLM']

Alternative specialized functions for BERT model only


*   BERT-specific class from Hugging Face Transformers
*   Coded for the BERT architecture

In [ ]:
from transformers import BertTokenizer, BertForSequenceClassification
model_name = "bert-base-cased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForSequenceClassification.from_pretrained(model_name,num_labels=2)

**We tokenize our data**

A DataCollator is a class that helps building batches of data

The data collator is a data processing pattern frequently used in Hugging Face

In [ ]:
from transformers import DataCollatorWithPadding
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

def preprocess_function(examples):
    return tokenizer(examples["text"], truncation=True)

In [ ]:
tokenized_train = train_data.map(preprocess_function, batched=True)
tokenized_test = test_data.map(preprocess_function , batched=True)

Map:   0%|          | 0/8530 [00:00<?, ? examples/s]

Map:   0%|          | 0/1066 [00:00<?, ? examples/s]

In [ ]:
cols = ["input_ids", "attention_mask", "token_type_ids", "label"]
tokenized_train.set_format(type="torch", columns=cols)
tokenized_test.set_format(type="torch", columns=cols)

Step 4: We define an **Evaluation function**

In [ ]:
import numpy as np
from sklearn.metrics import f1_score,accuracy_score, classification_report

def compute_metrics(eval_pred):
    logits, labels=eval_pred
    predictions = np.argmax(logits, axis=-1)
    return{
        "accuracy": accuracy_score(labels,predictions),
        "f1_macro": f1_score(labels,predictions,average="macro"),
        "f1_binary": f1_score(labels,predictions,average="binary")
    }

# **Training Process**

Hugging Face's Trainer class can be used to process to training

We define the **training parameters**

The **TrainingArguments** class is used to define the hyperparameters

In [ ]:
from transformers import TrainingArguments, Trainer

training_args=TrainingArguments(
    "model",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    eval_strategy="epoch",
    save_strategy="epoch",
    num_train_epochs=10,
    weight_decay=0.01,
    warmup_steps=100,
    logging_steps=10,
    metric_for_best_model="f1_macro",
    load_best_model_at_end=True,
    report_to="none"
)

**Trainer** is used to execute the training program

In [ ]:
trainer=Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

We train the model

In [ ]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=5340, training_loss=0.02331550265504045, metrics={'train_runtime': 1487.9157, 'train_samples_per_second': 57.329, 'train_steps_per_second': 3.589, 'total_flos': 2273050323914520.0, 'train_loss': 0.02331550265504045, 'epoch': 10.0})

We evaluate the model

In [ ]:
trainer.evaluate()

{'eval_loss': 1.2155694961547852,
 'eval_accuracy': 0.8574108818011257,
 'eval_f1_macro': 0.8573606724204106,
 'eval_f1_binary': 0.8546845124282982,
 'eval_runtime': 4.1319,
 'eval_samples_per_second': 257.995,
 'eval_steps_per_second': 8.229,
 'epoch': 10.0}

In [ ]:
from sklearn.metrics import classification_report

predictions = trainer.predict(tokenized_test)
preds = np.argmax(predictions.predictions, axis=-1)
print(classification_report(predictions.label_ids, preds))

NameError: name 'trainer' is not defined

In [ ]:
for log in trainer.state.log_history:
    if "eval_loss" in log:
        print(log)

{'eval_loss': 0.878846287727356, 'eval_accuracy': 0.8442776735459663, 'eval_f1_macro': 0.8441190979563074, 'eval_f1_binary': 0.8490909090909091, 'eval_runtime': 4.1404, 'eval_samples_per_second': 257.463, 'eval_steps_per_second': 8.212, 'epoch': 1.0, 'step': 534}
{'eval_loss': 0.8367926478385925, 'eval_accuracy': 0.850844277673546, 'eval_f1_macro': 0.8507748098962253, 'eval_f1_binary': 0.8475551294343241, 'eval_runtime': 4.3261, 'eval_samples_per_second': 246.413, 'eval_steps_per_second': 7.859, 'epoch': 2.0, 'step': 1068}
{'eval_loss': 1.015432596206665, 'eval_accuracy': 0.8395872420262664, 'eval_f1_macro': 0.8395758069129393, 'eval_f1_binary': 0.8409302325581396, 'eval_runtime': 5.1892, 'eval_samples_per_second': 205.426, 'eval_steps_per_second': 6.552, 'epoch': 3.0, 'step': 1602}
{'eval_loss': 1.1199076175689697, 'eval_accuracy': 0.8395872420262664, 'eval_f1_macro': 0.8395249644559672, 'eval_f1_binary': 0.8363636363636363, 'eval_runtime': 4.5802, 'eval_samples_per_second': 232.743, 'eval_steps_per_second': 7.423, 'epoch': 4.0, 'step': 2136}
{'eval_loss': 1.1881968975067139, 'eval_accuracy': 0.8395872420262664, 'eval_f1_macro': 0.839300874259806, 'eval_f1_binary': 0.8325171400587659, 'eval_runtime': 4.3747, 'eval_samples_per_second': 243.676, 'eval_steps_per_second': 7.772, 'epoch': 5.0, 'step': 2670}
{'eval_loss': 1.1761797666549683, 'eval_accuracy': 0.8545966228893058, 'eval_f1_macro': 0.8545504161550006, 'eval_f1_binary': 0.8519579751671442, 'eval_runtime': 4.4034, 'eval_samples_per_second': 242.085, 'eval_steps_per_second': 7.721, 'epoch': 6.0, 'step': 3204}
{'eval_loss': 1.2449601888656616, 'eval_accuracy': 0.849906191369606, 'eval_f1_macro': 0.8495481858630338, 'eval_f1_binary': 0.8422090729783037, 'eval_runtime': 4.4127, 'eval_samples_per_second': 241.577, 'eval_steps_per_second': 7.705, 'epoch': 7.0, 'step': 3738}
{'eval_loss': 1.2155033349990845, 'eval_accuracy': 0.8564727954971857, 'eval_f1_macro': 0.8564271849788071, 'eval_f1_binary': 0.8538681948424068, 'eval_runtime': 4.3933, 'eval_samples_per_second': 242.642, 'eval_steps_per_second': 7.739, 'epoch': 8.0, 'step': 4272}
{'eval_loss': 1.256319522857666, 'eval_accuracy': 0.8536585365853658, 'eval_f1_macro': 0.8536456573166611, 'eval_f1_binary': 0.8522727272727273, 'eval_runtime': 4.3835, 'eval_samples_per_second': 243.187, 'eval_steps_per_second': 7.756, 'epoch': 9.0, 'step': 4806}
{'eval_loss': 1.2667700052261353, 'eval_accuracy': 0.8555347091932458, 'eval_f1_macro': 0.8555326750796417, 'eval_f1_binary': 0.8549905838041432, 'eval_runtime': 4.3386, 'eval_samples_per_second': 245.702, 'eval_steps_per_second': 7.837, 'epoch': 10.0, 'step': 5340}
{'eval_loss': 1.2155694961547852, 'eval_accuracy': 0.8574108818011257, 'eval_f1_macro': 0.8573606724204106, 'eval_f1_binary': 0.8546845124282982, 'eval_runtime': 4.1319, 'eval_samples_per_second': 257.995, 'eval_steps_per_second': 8.229, 'epoch': 10.0, 'step': 5340}

In [ ]:
trainer.state.log_history

# Saving the model

In [ ]:
output_dir = "./bert-topic-cls"
trainer.save_model(output_dir)
tokenizer.save_pretrained(output_dir)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./bert-topic-cls/tokenizer_config.json', './bert-topic-cls/tokenizer.json')

In [ ]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

model = AutoModelForSequenceClassification.from_pretrained(output_dir)
tokenizer = AutoTokenizer.from_pretrained(output_dir)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [ ]:
from transformers import pipeline
model_path = "./bert-topic-cls"
classifier=pipeline("text-classification",model=model_path,tokenizer=model_path)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [ ]:
sentence = [
    "This movie is absolutely boring, the story is a nonsense and the actors are bad",
    "The story is very good, the landscape are great and the actors are good"
]

prediction = classifier(sentence)
print(prediction)

[{'label': 'LABEL_0', 'score': 0.9999817609786987}, {'label': 'LABEL_1', 'score': 0.9999784231185913}]

# Freezing Layers

We can freeze some layers of the network

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
model_name = "bert-base-cased"

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,num_labels=2)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
for name, param in model.named_parameters():
  print (name)

bert.embeddings.word_embeddings.weight
bert.embeddings.position_embeddings.weight
bert.embeddings.token_type_embeddings.weight
bert.embeddings.LayerNorm.weight
bert.embeddings.LayerNorm.bias
bert.encoder.layer.0.attention.self.query.weight
bert.encoder.layer.0.attention.self.query.bias
bert.encoder.layer.0.attention.self.key.weight
bert.encoder.layer.0.attention.self.key.bias
bert.encoder.layer.0.attention.self.value.weight
bert.encoder.layer.0.attention.self.value.bias
bert.encoder.layer.0.attention.output.dense.weight
bert.encoder.layer.0.attention.output.dense.bias
bert.encoder.layer.0.attention.output.LayerNorm.weight
bert.encoder.layer.0.attention.output.LayerNorm.bias
bert.encoder.layer.0.intermediate.dense.weight
bert.encoder.layer.0.intermediate.dense.bias
bert.encoder.layer.0.output.dense.weight
bert.encoder.layer.0.output.dense.bias
bert.encoder.layer.0.output.LayerNorm.weight
bert.encoder.layer.0.output.LayerNorm.bias
bert.encoder.layer.1.attention.self.query.weight
bert.encoder.layer.1.attention.self.query.bias
bert.encoder.layer.1.attention.self.key.weight
bert.encoder.layer.1.attention.self.key.bias
bert.encoder.layer.1.attention.self.value.weight
bert.encoder.layer.1.attention.self.value.bias
bert.encoder.layer.1.attention.output.dense.weight
bert.encoder.layer.1.attention.output.dense.bias
bert.encoder.layer.1.attention.output.LayerNorm.weight
bert.encoder.layer.1.attention.output.LayerNorm.bias
bert.encoder.layer.1.intermediate.dense.weight
bert.encoder.layer.1.intermediate.dense.bias
bert.encoder.layer.1.output.dense.weight
bert.encoder.layer.1.output.dense.bias
bert.encoder.layer.1.output.LayerNorm.weight
bert.encoder.layer.1.output.LayerNorm.bias
bert.encoder.layer.2.attention.self.query.weight
bert.encoder.layer.2.attention.self.query.bias
bert.encoder.layer.2.attention.self.key.weight
bert.encoder.layer.2.attention.self.key.bias
bert.encoder.layer.2.attention.self.value.weight
bert.encoder.layer.2.attention.self.value.bias
bert.encoder.layer.2.attention.output.dense.weight
bert.encoder.layer.2.attention.output.dense.bias
bert.encoder.layer.2.attention.output.LayerNorm.weight
bert.encoder.layer.2.attention.output.LayerNorm.bias
bert.encoder.layer.2.intermediate.dense.weight
bert.encoder.layer.2.intermediate.dense.bias
bert.encoder.layer.2.output.dense.weight
bert.encoder.layer.2.output.dense.bias
bert.encoder.layer.2.output.LayerNorm.weight
bert.encoder.layer.2.output.LayerNorm.bias
bert.encoder.layer.3.attention.self.query.weight
bert.encoder.layer.3.attention.self.query.bias
bert.encoder.layer.3.attention.self.key.weight
bert.encoder.layer.3.attention.self.key.bias
bert.encoder.layer.3.attention.self.value.weight
bert.encoder.layer.3.attention.self.value.bias
bert.encoder.layer.3.attention.output.dense.weight
bert.encoder.layer.3.attention.output.dense.bias
bert.encoder.layer.3.attention.output.LayerNorm.weight
bert.encoder.layer.3.attention.output.LayerNorm.bias
bert.encoder.layer.3.intermediate.dense.weight
bert.encoder.layer.3.intermediate.dense.bias
bert.encoder.layer.3.output.dense.weight
bert.encoder.layer.3.output.dense.bias
bert.encoder.layer.3.output.LayerNorm.weight
bert.encoder.layer.3.output.LayerNorm.bias
bert.encoder.layer.4.attention.self.query.weight
bert.encoder.layer.4.attention.self.query.bias
bert.encoder.layer.4.attention.self.key.weight
bert.encoder.layer.4.attention.self.key.bias
bert.encoder.layer.4.attention.self.value.weight
bert.encoder.layer.4.attention.self.value.bias
bert.encoder.layer.4.attention.output.dense.weight
bert.encoder.layer.4.attention.output.dense.bias
bert.encoder.layer.4.attention.output.LayerNorm.weight
bert.encoder.layer.4.attention.output.LayerNorm.bias
bert.encoder.layer.4.intermediate.dense.weight
bert.encoder.layer.4.intermediate.dense.bias
bert.encoder.layer.4.output.dense.weight
bert.encoder.layer.4.output.dense.bias
bert.encoder.layer.4.output.LayerNorm.weight
bert.encoder.layer.4.output.LayerNorm.bias
bert.encoder.layer.5.attention.self.query.weight
bert.encoder.layer.5.attention.self.query.bias
bert.encoder.layer.5.attention.self.key.weight
bert.encoder.layer.5.attention.self.key.bias
bert.encoder.layer.5.attention.self.value.weight
bert.encoder.layer.5.attention.self.value.bias
bert.encoder.layer.5.attention.output.dense.weight
bert.encoder.layer.5.attention.output.dense.bias
bert.encoder.layer.5.attention.output.LayerNorm.weight
bert.encoder.layer.5.attention.output.LayerNorm.bias
bert.encoder.layer.5.intermediate.dense.weight
bert.encoder.layer.5.intermediate.dense.bias
bert.encoder.layer.5.output.dense.weight
bert.encoder.layer.5.output.dense.bias
bert.encoder.layer.5.output.LayerNorm.weight
bert.encoder.layer.5.output.LayerNorm.bias
bert.encoder.layer.6.attention.self.query.weight
bert.encoder.layer.6.attention.self.query.bias
bert.encoder.layer.6.attention.self.key.weight
bert.encoder.layer.6.attention.self.key.bias
bert.encoder.layer.6.attention.self.value.weight
bert.encoder.layer.6.attention.self.value.bias
bert.encoder.layer.6.attention.output.dense.weight
bert.encoder.layer.6.attention.output.dense.bias
bert.encoder.layer.6.attention.output.LayerNorm.weight
bert.encoder.layer.6.attention.output.LayerNorm.bias
bert.encoder.layer.6.intermediate.dense.weight
bert.encoder.layer.6.intermediate.dense.bias
bert.encoder.layer.6.output.dense.weight
bert.encoder.layer.6.output.dense.bias
bert.encoder.layer.6.output.LayerNorm.weight
bert.encoder.layer.6.output.LayerNorm.bias
bert.encoder.layer.7.attention.self.query.weight
bert.encoder.layer.7.attention.self.query.bias
bert.encoder.layer.7.attention.self.key.weight
bert.encoder.layer.7.attention.self.key.bias
bert.encoder.layer.7.attention.self.value.weight
bert.encoder.layer.7.attention.self.value.bias
bert.encoder.layer.7.attention.output.dense.weight
bert.encoder.layer.7.attention.output.dense.bias
bert.encoder.layer.7.attention.output.LayerNorm.weight
bert.encoder.layer.7.attention.output.LayerNorm.bias
bert.encoder.layer.7.intermediate.dense.weight
bert.encoder.layer.7.intermediate.dense.bias
bert.encoder.layer.7.output.dense.weight
bert.encoder.layer.7.output.dense.bias
bert.encoder.layer.7.output.LayerNorm.weight
bert.encoder.layer.7.output.LayerNorm.bias
bert.encoder.layer.8.attention.self.query.weight
bert.encoder.layer.8.attention.self.query.bias
bert.encoder.layer.8.attention.self.key.weight
bert.encoder.layer.8.attention.self.key.bias
bert.encoder.layer.8.attention.self.value.weight
bert.encoder.layer.8.attention.self.value.bias
bert.encoder.layer.8.attention.output.dense.weight
bert.encoder.layer.8.attention.output.dense.bias
bert.encoder.layer.8.attention.output.LayerNorm.weight
bert.encoder.layer.8.attention.output.LayerNorm.bias
bert.encoder.layer.8.intermediate.dense.weight
bert.encoder.layer.8.intermediate.dense.bias
bert.encoder.layer.8.output.dense.weight
bert.encoder.layer.8.output.dense.bias
bert.encoder.layer.8.output.LayerNorm.weight
bert.encoder.layer.8.output.LayerNorm.bias
bert.encoder.layer.9.attention.self.query.weight
bert.encoder.layer.9.attention.self.query.bias
bert.encoder.layer.9.attention.self.key.weight
bert.encoder.layer.9.attention.self.key.bias
bert.encoder.layer.9.attention.self.value.weight
bert.encoder.layer.9.attention.self.value.bias
bert.encoder.layer.9.attention.output.dense.weight
bert.encoder.layer.9.attention.output.dense.bias
bert.encoder.layer.9.attention.output.LayerNorm.weight
bert.encoder.layer.9.attention.output.LayerNorm.bias
bert.encoder.layer.9.intermediate.dense.weight
bert.encoder.layer.9.intermediate.dense.bias
bert.encoder.layer.9.output.dense.weight
bert.encoder.layer.9.output.dense.bias
bert.encoder.layer.9.output.LayerNorm.weight
bert.encoder.layer.9.output.LayerNorm.bias
bert.encoder.layer.10.attention.self.query.weight
bert.encoder.layer.10.attention.self.query.bias
bert.encoder.layer.10.attention.self.key.weight
bert.encoder.layer.10.attention.self.key.bias
bert.encoder.layer.10.attention.self.value.weight
bert.encoder.layer.10.attention.self.value.bias
bert.encoder.layer.10.attention.output.dense.weight
bert.encoder.layer.10.attention.output.dense.bias
bert.encoder.layer.10.attention.output.LayerNorm.weight
bert.encoder.layer.10.attention.output.LayerNorm.bias
bert.encoder.layer.10.intermediate.dense.weight
bert.encoder.layer.10.intermediate.dense.bias
bert.encoder.layer.10.output.dense.weight
bert.encoder.layer.10.output.dense.bias
bert.encoder.layer.10.output.LayerNorm.weight
bert.encoder.layer.10.output.LayerNorm.bias
bert.encoder.layer.11.attention.self.query.weight
bert.encoder.layer.11.attention.self.query.bias
bert.encoder.layer.11.attention.self.key.weight
bert.encoder.layer.11.attention.self.key.bias
bert.encoder.layer.11.attention.self.value.weight
bert.encoder.layer.11.attention.self.value.bias
bert.encoder.layer.11.attention.output.dense.weight
bert.encoder.layer.11.attention.output.dense.bias
bert.encoder.layer.11.attention.output.LayerNorm.weight
bert.encoder.layer.11.attention.output.LayerNorm.bias
bert.encoder.layer.11.intermediate.dense.weight
bert.encoder.layer.11.intermediate.dense.bias
bert.encoder.layer.11.output.dense.weight
bert.encoder.layer.11.output.dense.bias
bert.encoder.layer.11.output.LayerNorm.weight
bert.encoder.layer.11.output.LayerNorm.bias
bert.pooler.dense.weight
bert.pooler.dense.bias
classifier.weight
classifier.bias

We freeze the pretrained BERT model and train only the classifier

In [ ]:
for name, param in model.named_parameters():
  if "classifier" not in name:
    param.requires_grad = False

In [ ]:
from transformers import TrainingArguments, Trainer

training_args=TrainingArguments(
    "model",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    eval_strategy="epoch",
    save_strategy="epoch",
    num_train_epochs=5,
    weight_decay=0.01,
    warmup_steps=100,
    logging_steps=10,
    metric_for_best_model="f1_macro",
    load_best_model_at_end=True,
    report_to="none"
)

In [ ]:
from transformers import TrainingArguments, Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

In [ ]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=2670, training_loss=0.6658054878649193, metrics={'train_runtime': 217.922, 'train_samples_per_second': 195.712, 'train_steps_per_second': 12.252, 'total_flos': 1136157731479560.0, 'train_loss': 0.6658054878649193, 'epoch': 5.0})

In [ ]:
trainer.evaluate()

{'eval_loss': 0.6522194743156433,
 'eval_accuracy': 0.625703564727955,
 'eval_f1_macro': 0.6252019015980297,
 'eval_f1_binary': 0.611489776046738,
 'eval_runtime': 4.2293,
 'eval_samples_per_second': 252.049,
 'eval_steps_per_second': 8.039,
 'epoch': 5.0}

We freeze the first ten encoder blocks.

The 11th encoder block begins at index 165

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,num_labels=2)
tokenizer = AutoTokenizer.from_pretrained(model_name)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
for index,(name,param) in enumerate(model.named_parameters()):
  print(index,name)

0 bert.embeddings.word_embeddings.weight
1 bert.embeddings.position_embeddings.weight
2 bert.embeddings.token_type_embeddings.weight
3 bert.embeddings.LayerNorm.weight
4 bert.embeddings.LayerNorm.bias
5 bert.encoder.layer.0.attention.self.query.weight
6 bert.encoder.layer.0.attention.self.query.bias
7 bert.encoder.layer.0.attention.self.key.weight
8 bert.encoder.layer.0.attention.self.key.bias
9 bert.encoder.layer.0.attention.self.value.weight
10 bert.encoder.layer.0.attention.self.value.bias
11 bert.encoder.layer.0.attention.output.dense.weight
12 bert.encoder.layer.0.attention.output.dense.bias
13 bert.encoder.layer.0.attention.output.LayerNorm.weight
14 bert.encoder.layer.0.attention.output.LayerNorm.bias
15 bert.encoder.layer.0.intermediate.dense.weight
16 bert.encoder.layer.0.intermediate.dense.bias
17 bert.encoder.layer.0.output.dense.weight
18 bert.encoder.layer.0.output.dense.bias
19 bert.encoder.layer.0.output.LayerNorm.weight
20 bert.encoder.layer.0.output.LayerNorm.bias
21 bert.encoder.layer.1.attention.self.query.weight
22 bert.encoder.layer.1.attention.self.query.bias
23 bert.encoder.layer.1.attention.self.key.weight
24 bert.encoder.layer.1.attention.self.key.bias
25 bert.encoder.layer.1.attention.self.value.weight
26 bert.encoder.layer.1.attention.self.value.bias
27 bert.encoder.layer.1.attention.output.dense.weight
28 bert.encoder.layer.1.attention.output.dense.bias
29 bert.encoder.layer.1.attention.output.LayerNorm.weight
30 bert.encoder.layer.1.attention.output.LayerNorm.bias
31 bert.encoder.layer.1.intermediate.dense.weight
32 bert.encoder.layer.1.intermediate.dense.bias
33 bert.encoder.layer.1.output.dense.weight
34 bert.encoder.layer.1.output.dense.bias
35 bert.encoder.layer.1.output.LayerNorm.weight
36 bert.encoder.layer.1.output.LayerNorm.bias
37 bert.encoder.layer.2.attention.self.query.weight
38 bert.encoder.layer.2.attention.self.query.bias
39 bert.encoder.layer.2.attention.self.key.weight
40 bert.encoder.layer.2.attention.self.key.bias
41 bert.encoder.layer.2.attention.self.value.weight
42 bert.encoder.layer.2.attention.self.value.bias
43 bert.encoder.layer.2.attention.output.dense.weight
44 bert.encoder.layer.2.attention.output.dense.bias
45 bert.encoder.layer.2.attention.output.LayerNorm.weight
46 bert.encoder.layer.2.attention.output.LayerNorm.bias
47 bert.encoder.layer.2.intermediate.dense.weight
48 bert.encoder.layer.2.intermediate.dense.bias
49 bert.encoder.layer.2.output.dense.weight
50 bert.encoder.layer.2.output.dense.bias
51 bert.encoder.layer.2.output.LayerNorm.weight
52 bert.encoder.layer.2.output.LayerNorm.bias
53 bert.encoder.layer.3.attention.self.query.weight
54 bert.encoder.layer.3.attention.self.query.bias
55 bert.encoder.layer.3.attention.self.key.weight
56 bert.encoder.layer.3.attention.self.key.bias
57 bert.encoder.layer.3.attention.self.value.weight
58 bert.encoder.layer.3.attention.self.value.bias
59 bert.encoder.layer.3.attention.output.dense.weight
60 bert.encoder.layer.3.attention.output.dense.bias
61 bert.encoder.layer.3.attention.output.LayerNorm.weight
62 bert.encoder.layer.3.attention.output.LayerNorm.bias
63 bert.encoder.layer.3.intermediate.dense.weight
64 bert.encoder.layer.3.intermediate.dense.bias
65 bert.encoder.layer.3.output.dense.weight
66 bert.encoder.layer.3.output.dense.bias
67 bert.encoder.layer.3.output.LayerNorm.weight
68 bert.encoder.layer.3.output.LayerNorm.bias
69 bert.encoder.layer.4.attention.self.query.weight
70 bert.encoder.layer.4.attention.self.query.bias
71 bert.encoder.layer.4.attention.self.key.weight
72 bert.encoder.layer.4.attention.self.key.bias
73 bert.encoder.layer.4.attention.self.value.weight
74 bert.encoder.layer.4.attention.self.value.bias
75 bert.encoder.layer.4.attention.output.dense.weight
76 bert.encoder.layer.4.attention.output.dense.bias
77 bert.encoder.layer.4.attention.output.LayerNorm.weight
78 bert.encoder.layer.4.attention.output.LayerNorm.bias
79 bert.encoder.layer.4.intermediate.dense.weight
80 bert.encoder.layer.4.intermediate.dense.bias
81 bert.encoder.layer.4.output.dense.weight
82 bert.encoder.layer.4.output.dense.bias
83 bert.encoder.layer.4.output.LayerNorm.weight
84 bert.encoder.layer.4.output.LayerNorm.bias
85 bert.encoder.layer.5.attention.self.query.weight
86 bert.encoder.layer.5.attention.self.query.bias
87 bert.encoder.layer.5.attention.self.key.weight
88 bert.encoder.layer.5.attention.self.key.bias
89 bert.encoder.layer.5.attention.self.value.weight
90 bert.encoder.layer.5.attention.self.value.bias
91 bert.encoder.layer.5.attention.output.dense.weight
92 bert.encoder.layer.5.attention.output.dense.bias
93 bert.encoder.layer.5.attention.output.LayerNorm.weight
94 bert.encoder.layer.5.attention.output.LayerNorm.bias
95 bert.encoder.layer.5.intermediate.dense.weight
96 bert.encoder.layer.5.intermediate.dense.bias
97 bert.encoder.layer.5.output.dense.weight
98 bert.encoder.layer.5.output.dense.bias
99 bert.encoder.layer.5.output.LayerNorm.weight
100 bert.encoder.layer.5.output.LayerNorm.bias
101 bert.encoder.layer.6.attention.self.query.weight
102 bert.encoder.layer.6.attention.self.query.bias
103 bert.encoder.layer.6.attention.self.key.weight
104 bert.encoder.layer.6.attention.self.key.bias
105 bert.encoder.layer.6.attention.self.value.weight
106 bert.encoder.layer.6.attention.self.value.bias
107 bert.encoder.layer.6.attention.output.dense.weight
108 bert.encoder.layer.6.attention.output.dense.bias
109 bert.encoder.layer.6.attention.output.LayerNorm.weight
110 bert.encoder.layer.6.attention.output.LayerNorm.bias
111 bert.encoder.layer.6.intermediate.dense.weight
112 bert.encoder.layer.6.intermediate.dense.bias
113 bert.encoder.layer.6.output.dense.weight
114 bert.encoder.layer.6.output.dense.bias
115 bert.encoder.layer.6.output.LayerNorm.weight
116 bert.encoder.layer.6.output.LayerNorm.bias
117 bert.encoder.layer.7.attention.self.query.weight
118 bert.encoder.layer.7.attention.self.query.bias
119 bert.encoder.layer.7.attention.self.key.weight
120 bert.encoder.layer.7.attention.self.key.bias
121 bert.encoder.layer.7.attention.self.value.weight
122 bert.encoder.layer.7.attention.self.value.bias
123 bert.encoder.layer.7.attention.output.dense.weight
124 bert.encoder.layer.7.attention.output.dense.bias
125 bert.encoder.layer.7.attention.output.LayerNorm.weight
126 bert.encoder.layer.7.attention.output.LayerNorm.bias
127 bert.encoder.layer.7.intermediate.dense.weight
128 bert.encoder.layer.7.intermediate.dense.bias
129 bert.encoder.layer.7.output.dense.weight
130 bert.encoder.layer.7.output.dense.bias
131 bert.encoder.layer.7.output.LayerNorm.weight
132 bert.encoder.layer.7.output.LayerNorm.bias
133 bert.encoder.layer.8.attention.self.query.weight
134 bert.encoder.layer.8.attention.self.query.bias
135 bert.encoder.layer.8.attention.self.key.weight
136 bert.encoder.layer.8.attention.self.key.bias
137 bert.encoder.layer.8.attention.self.value.weight
138 bert.encoder.layer.8.attention.self.value.bias
139 bert.encoder.layer.8.attention.output.dense.weight
140 bert.encoder.layer.8.attention.output.dense.bias
141 bert.encoder.layer.8.attention.output.LayerNorm.weight
142 bert.encoder.layer.8.attention.output.LayerNorm.bias
143 bert.encoder.layer.8.intermediate.dense.weight
144 bert.encoder.layer.8.intermediate.dense.bias
145 bert.encoder.layer.8.output.dense.weight
146 bert.encoder.layer.8.output.dense.bias
147 bert.encoder.layer.8.output.LayerNorm.weight
148 bert.encoder.layer.8.output.LayerNorm.bias
149 bert.encoder.layer.9.attention.self.query.weight
150 bert.encoder.layer.9.attention.self.query.bias
151 bert.encoder.layer.9.attention.self.key.weight
152 bert.encoder.layer.9.attention.self.key.bias
153 bert.encoder.layer.9.attention.self.value.weight
154 bert.encoder.layer.9.attention.self.value.bias
155 bert.encoder.layer.9.attention.output.dense.weight
156 bert.encoder.layer.9.attention.output.dense.bias
157 bert.encoder.layer.9.attention.output.LayerNorm.weight
158 bert.encoder.layer.9.attention.output.LayerNorm.bias
159 bert.encoder.layer.9.intermediate.dense.weight
160 bert.encoder.layer.9.intermediate.dense.bias
161 bert.encoder.layer.9.output.dense.weight
162 bert.encoder.layer.9.output.dense.bias
163 bert.encoder.layer.9.output.LayerNorm.weight
164 bert.encoder.layer.9.output.LayerNorm.bias
165 bert.encoder.layer.10.attention.self.query.weight
166 bert.encoder.layer.10.attention.self.query.bias
167 bert.encoder.layer.10.attention.self.key.weight
168 bert.encoder.layer.10.attention.self.key.bias
169 bert.encoder.layer.10.attention.self.value.weight
170 bert.encoder.layer.10.attention.self.value.bias
171 bert.encoder.layer.10.attention.output.dense.weight
172 bert.encoder.layer.10.attention.output.dense.bias
173 bert.encoder.layer.10.attention.output.LayerNorm.weight
174 bert.encoder.layer.10.attention.output.LayerNorm.bias
175 bert.encoder.layer.10.intermediate.dense.weight
176 bert.encoder.layer.10.intermediate.dense.bias
177 bert.encoder.layer.10.output.dense.weight
178 bert.encoder.layer.10.output.dense.bias
179 bert.encoder.layer.10.output.LayerNorm.weight
180 bert.encoder.layer.10.output.LayerNorm.bias
181 bert.encoder.layer.11.attention.self.query.weight
182 bert.encoder.layer.11.attention.self.query.bias
183 bert.encoder.layer.11.attention.self.key.weight
184 bert.encoder.layer.11.attention.self.key.bias
185 bert.encoder.layer.11.attention.self.value.weight
186 bert.encoder.layer.11.attention.self.value.bias
187 bert.encoder.layer.11.attention.output.dense.weight
188 bert.encoder.layer.11.attention.output.dense.bias
189 bert.encoder.layer.11.attention.output.LayerNorm.weight
190 bert.encoder.layer.11.attention.output.LayerNorm.bias
191 bert.encoder.layer.11.intermediate.dense.weight
192 bert.encoder.layer.11.intermediate.dense.bias
193 bert.encoder.layer.11.output.dense.weight
194 bert.encoder.layer.11.output.dense.bias
195 bert.encoder.layer.11.output.LayerNorm.weight
196 bert.encoder.layer.11.output.LayerNorm.bias
197 bert.pooler.dense.weight
198 bert.pooler.dense.bias
199 classifier.weight
200 classifier.bias

In [ ]:
for index,(name,param) in enumerate(model.named_parameters()):
  if index<165:
    param.requires_grad=False

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()
trainer.evaluate()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

{'eval_loss': 0.38983863592147827,
 'eval_accuracy': 0.8461538461538461,
 'eval_f1_macro': 0.8461099687332752,
 'eval_f1_binary': 0.8435114503816794,
 'eval_runtime': 4.3013,
 'eval_samples_per_second': 247.832,
 'eval_steps_per_second': 7.905,
 'epoch': 5.0}